package generator

import "text/template"

var tmpl = template.Must(template.New("").Parse(`
// Code generated by protoc-gen-rest. DO NOT EDIT.
// versions:
//  protoc-gen-rest v0.0.1
// source: {{ .Name }}

package {{ .Package }}

import (
	"context"
)

{{ if true }}
{{ range .Service -}}
type {{ .Name}}Server interface {
	{{- range .Method }}
	{{ .Name }}(ctx context.Context, req string) (string, error)
	{{- end }}
}
{{ end }}
{{ end }}
`))
